---

*Name: Achintya Kamath*

*Roll Number: R030*

*MBA Tech Artificial Intelligence*

*Subject: Deep Learning*

*Lab 01 - Tensorflow 2.0 [Basics]*

*Date: 19-07-2023*

---

In [90]:
'''
Name: Achintya Kamath
Roll Number: R030
MBA Tech Artificial Intelligence
Subject: Deep Learning
Lab 01 - Tensorflow 2.0 [Basics]
Date: 19-07-2023
'''

'\nName: Achintya Kamath\nRoll Number: R030\nMBA Tech Artificial Intelligence\nSubject: Deep Learning\nLab 01 - Tensorflow 2.0 [Basics]\nDate: 19-07-2023\n'

# ***TASK 1***

*Perform basic operations using Tensorflow*

*(Defining constants, variables, concatenation, add, multiply, reduce mean, reduce sum)*

In [91]:
import tensorflow as tf
import numpy as np
print("This program utilises Tensorflow verison", tf.__version__, " ")

This program utilises Tensorflow verison 2.13.0  


In [92]:
#Constants

In [93]:
const = tf.constant([[7,8,3], [5,9,1]])
print(const)

tf.Tensor(
[[7 8 3]
 [5 9 1]], shape=(2, 3), dtype=int32)


In [94]:
print(const.shape)

(2, 3)


In [95]:
print(const.dtype)

<dtype: 'int32'>


In [96]:
print(const.numpy())

[[7 8 3]
 [5 9 1]]


In [97]:
#Variables

In [98]:
varb = tf.Variable([0.0, 0.0, 0.0])
varb.assign([1,5,6])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([1., 5., 6.], dtype=float32)>

In [99]:
print(varb)

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 5., 6.], dtype=float32)>


In [100]:
print(varb.numpy())

[1. 5. 6.]


In [101]:
varb.assign_add([1,1,1])
print(varb.numpy())

[2. 6. 7.]


In [102]:
#Concatenation (columns and rows)

In [103]:
A = tf.constant([[3,4,5], [1,2,3]])
B = tf.Variable([[1,1,1], [2,3,4]])

In [104]:
AB_concat_col = tf.concat([A,B], axis=1)
print(AB_concat_col.numpy())

[[3 4 5 1 1 1]
 [1 2 3 2 3 4]]


In [105]:
AB_concat_row = tf.concat([A,B], axis=0)
print(AB_concat_row.numpy())

[[3 4 5]
 [1 2 3]
 [1 1 1]
 [2 3 4]]


In [106]:
reshaped_concat = tf.reshape(AB_concat_row, shape = [1,12])
print(reshaped_concat.numpy())

[[3 4 5 1 2 3 1 1 1 2 3 4]]


In [107]:
#Addition

In [108]:
A = tf.constant([[3,4,5], [1,2,3]])
B = tf.constant([[1,1,1], [2,3,4]])
C = tf.constant([[5,1,5], [2,2,3]])

In [109]:
print(A.numpy())
print("\n", B.numpy())

[[3 4 5]
 [1 2 3]]

 [[1 1 1]
 [2 3 4]]


In [110]:
A_plus_B = tf.add(A,B)
print(A_plus_B.numpy())

[[4 5 6]
 [3 5 7]]


In [111]:
print(C.numpy())

[[5 1 5]
 [2 2 3]]


In [112]:
APB_plus_C = tf.add(A_plus_B, C)
print(APB_plus_C.numpy())

[[ 9  6 11]
 [ 5  7 10]]


In [113]:
variation_APBPC = tf.add(A, B, C)
print(variation_APBPC.numpy())

[[4 5 6]
 [3 5 7]]


In [114]:
#Multiplication

In [115]:
A_multi_B = tf.multiply(A,B)
print(A.numpy(), "\n\n", B.numpy(), '\n')
print(A_multi_B.numpy())

[[3 4 5]
 [1 2 3]] 

 [[1 1 1]
 [2 3 4]] 

[[ 3  4  5]
 [ 2  6 12]]


In [116]:
AMB_multi_C = tf.multiply(A_multi_B,C)
print(C.numpy(), '\n')
print(AMB_multi_C.numpy())

[[5 1 5]
 [2 2 3]] 

[[15  4 25]
 [ 4 12 36]]


In [117]:
#Reducing Mean

In [118]:
G = tf.constant([[1.55, 2.54, 8.35, 9.25], [1.00, 2.00, 8.95, 4.00]])
print(G.numpy())

[[1.55 2.54 8.35 9.25]
 [1.   2.   8.95 4.  ]]


In [119]:
reduced_G = tf.reduce_mean(G, 0)
print(reduced_G.numpy())

[1.275 2.27  8.65  6.625]


In [120]:
#Reducing Sum

In [121]:
S = tf.constant([[5.55, 3.54, 7.35, 9.25], [5.00, 6.00, 8.95, 4.00]])
SS = tf.constant([[1.55, 2.54, 8.35, 9.25], [1.00, 2.00, 8.95, 4.00]])

In [122]:
print(S.numpy())

[[5.55 3.54 7.35 9.25]
 [5.   6.   8.95 4.  ]]


In [123]:
print(SS.numpy())

[[1.55 2.54 8.35 9.25]
 [1.   2.   8.95 4.  ]]


In [124]:
RS_3 = tf.reduce_sum([S, SS])
print(RS_3.numpy())

87.28


# ***TASK 2***

*Perform linear algebra operations using Tensorflow*

*(Transpose of a matrix, matrix multiplication, element-wise multiplication, determinant of a matrix)*

In [125]:
#Transpose of a Matrix

In [126]:
a_const = tf.constant([[2,7], [5,9]])
print(a_const.numpy())

[[2 7]
 [5 9]]


In [127]:
a_trans = tf.transpose(a_const)
print(a_trans.numpy())

[[2 5]
 [7 9]]


In [128]:
#Matrix Multiplication

In [129]:
b_const = tf.constant([[3,8], [7,2]])
print(b_const.numpy())

[[3 8]
 [7 2]]


In [130]:
a_mul_b = tf.matmul(a_const, b_const)
print(a_mul_b.numpy())

[[55 30]
 [78 58]]


In [131]:
#Element-Wise Multiplication

In [132]:
b_const = tf.constant([[3,8], [7,2]])
mu = tf.constant([[10,6]])
print(mu.numpy())

[[10  6]]


In [133]:
ele_mul = tf.multiply(b_const,mu)
print(ele_mul.numpy())

[[30 48]
 [70 12]]


In [134]:
#Determinant

In [135]:
ele_mul = tf.cast(ele_mul, tf.float32)
det = tf.linalg.det(ele_mul)
print(det.numpy())

-3000.0002


# ***Task 3***

*Perform derivative and higher order derivative for function,*

*f(x) = x^3*

*using gradient tape of Tensorflow*

In [136]:
#Obtaining derivative and higher order derivative

In [145]:
#using concept f(x) = x^3
const_x = tf.constant(4.0)
with tf.GradientTape() as tape:
    tape.watch(const_x)
    y = const_x**3

grad = tape.gradient(y, const_x)
print("The Derivative is =", grad.numpy())

#Going for higher order now...
new_x = tf.Variable(4.0, trainable=True)
with tf.GradientTape() as tapeOne:
    with tf.GradientTape() as tapeTwo:
        y = new_x**3
        order = tapeTwo.gradient(y, new_x)  # First Order

Higher_Order = tapeOne.gradient(order, new_x)  # Second Order
print("The Higher Order Derivative is =", Higher_Order.numpy())


The Derivative is = 48.0
The Higher Order Derivative is = 24.0


# ***Task 4***

*Compute WX+b using Tensorflow where W, X, and b are drawn from a random normal distribution.*

*W is of shape (4, 3), X is (3,1) and b is (4,1)*

In [138]:
#Compute WX+b using Tensorflow where W, X, and b are drawn from a
#random normal distribution. W is of shape (4, 3), X is (3,1) and b is (4,1)

In [139]:
#Using np.random.randn to randomly assign constants

w_mat = tf.constant(np.random.randn(4,3))
x_mat = tf.constant(np.random.randn(3,1))
b_mat = tf.constant(np.random.randn(4,1))

print(w_mat.numpy(), "\n")
print(x_mat.numpy(), "\n")
print(b_mat.numpy())

[[-0.82013122 -1.02223737 -0.41331467]
 [ 0.88650879 -0.33673666  0.45403992]
 [ 0.24943101 -1.11963644 -1.42534854]
 [-0.34615732 -0.22962514 -0.50532886]] 

[[ 0.66514611]
 [ 1.48351153]
 [-1.10451872]] 

[[ 0.40493862]
 [-0.47161172]
 [-0.0919803 ]
 [ 1.43485834]]


In [140]:
WX = tf.matmul(w_mat,x_mat)
print(WX.numpy())

[[-1.60549423]
 [-0.41139044]
 [ 0.07923864]
 [-0.01275155]]


In [141]:
WX_plus_b = tf.add(WX, b_mat)
print(WX_plus_b.numpy())

[[-1.2005556 ]
 [-0.88300216]
 [-0.01274166]
 [ 1.42210679]]


# ***Task 5***

*Compute Gradient of sigmoid function using Tensor flow*

In [142]:
#Formula: f(x) = 1/1+exp(-x)

def sigma_gradient(someThing):
    with tf.GradientTape() as tape_sig:
        f = (1 / 1 + (tf.math.exp(-someThing)))
    sigma_grad = tape_sig.gradient(f, someThing)
    return sigma_grad.numpy()

variable_but_constant = tf.Variable(4.0, trainable=True)

print("Gradient of the sigmoid", variable_but_constant.numpy(), " is ", sigma_gradient(variable_but_constant))

Gradient of the sigmoid 4.0  is  -0.01831564


# ***Task 6***

*Identify two research paper based on deep learning.*

*State for which application they have used deep learning.*

*(Cite the papers)*

***Research Paper 1:***
*Smith, M. J., & Geach, J. E. (2023). Astronomia ex machina: a history, primer and outlook on neural networks in astronomy. Royal Society Open Science, 10(5), 221454.*

***Research Paper 2:***
*Ofman, L., Averbuch, A., Shliselberg, A., Benaun, I., Segev, D., & Rissman, A. (2022). Automated identification of transiting exoplanet candidates in NASA Transiting Exoplanets Survey Satellite (TESS) data with machine learning methods. New Astronomy, 91, 101693.*